# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'GalleryModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GalleryModule
  pod 'GITSFramework', :path => '../GITSFramework'
  pod 'Shimmer'
  pod 'TOCropViewController'

end

target 'GalleryModuleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GalleryModule
  pod 'GalleryModule', :path => '../GalleryModule'

end

# Workaround for Cocoapods issue #7606
post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |bc|
        bc.build_settings.delete('CODE_SIGNING_ALLOWED')
        bc.build_settings.delete('CODE_SIGNING_REQUIRED')
        bc.build_settings['SWIFT_VERSION'] = '5.0'
        bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
